from pathlib import Path
import json,csv,hashlib,shutil,collections,os,tempfile
P=Path('/workspace/scratch/0b54847633d9/BASS_HE_POST_DATABASE_A1_B1_20261001_v1'); B=P/'B1'; W=Path('/workspace/scratch/0b54847633d9/b1_work')
def put(path,data):
 path.parent.mkdir(parents=True,exist_ok=True)
 fd,tmp=tempfile.mkstemp(dir=path.parent,prefix='.tmp_')
 with os.fdopen(fd,'wb') as f:f.write(data);f.flush();os.fsync(f.fileno())
 os.replace(tmp,path)
def js(path,obj):put(path,(json.dumps(obj,ensure_ascii=False,indent=2)+'\n').encode())
def csvput(path,rows,fields):
 import io
 s=io.StringIO(newline='');w=csv.DictWriter(s,fieldnames=fields);w.writeheader();w.writerows(rows);put(path,s.getvalue().encode('utf-8-sig'))
meta=json.loads((W/'metadata_review/metadata_review.json').read_text()); M={m['source_id']:m for m in meta['results']}
finding=json.loads((W/'metadata_review/p07p08/findings.json').read_text())
js(B/'evidence/METADATA_REVIEW.json',meta);js(B/'evidence/P07_P08_SOURCE_REVIEW.json',finding)
p08=finding['P08'];js(B/'evidence/P08_verified_cells.json',p08['capture_native_table'])
shutil.copy2(W/'metadata_review/p07p08/P08_page_5.png',B/'evidence/P08_page5.png')
rows=list(csv.DictReader((B/'EXACT_SOURCE_CELLS.csv').open(encoding='utf-8-sig')));fields=list(rows[0]);rows=[r for r in rows if r['source_id']!='P08']
for r in rows:
 if r['source_id']=='P04':
  r['energy_frame']='NATIVE_IMPACT_ENERGY_KEV_PER_U;LAB_VS_CM_NOT_EXPLICIT;NO_CONVERSION'
  r['target_initial_state']='H nativeP04;H(1s) bound by P01 Liu2024 introduction cross-reference'
  r['isotope']='alpha/4He context;H notD/T;exact nuclear masses unspecified'
  if r['method']=='AOCC-A':r['method']='AOCC-A;Toshima1995 NIFS-DATA-26 values imported by Minami2008'
files={f['id']:f for f in json.loads((B/'SOURCE_MANIFEST.json').read_text())['files']};s=files['P08']
for rr in p08['capture_native_table']['native_rows']:
 for col in ['1s','2s','2p','3s','3p','3d','beyond_3d','All']:
  r={k:'' for k in fields};r.update(source_id='P08',doi=s['doi'],source_path=s['path_relative_to_immutable_v3'],source_sha256=s['sha256'],pdf_page='5',printed_page='062702-5',table='II',source_row='20keV;'+str(rr['basis_states'])+'states',source_column=col,energy_token='20',energy_unit='keV',energy_frame='alpha projectile laboratory energy;A4 normalization only conditional;no conversion',isotope='alpha particle / proton species;exact masses unspecified',projectile='He2+',target_initial_state='H(1s)',final_state='He+('+col+');native printed observable',observable='electron_capture_cross_section',value_token=rr[col],cross_section_unit='10^-17 cm^2',method=str(rr['basis_states'])+'-state coupled-Sturmian;'+rr['basis_role'],uncertainty_kind='NO_ROW_CERTIFICATE;151-state n3 unreliable per author;All/beyond3d source-authored threshold/tail correction',evidence_status='LITERATURE_SUPPORTED',transcription_status='TABLEII_20KEV_TWO_ROWS_VISUALLY_VERIFIED_BY_SOURCE_READER_AND_ROOT',benchmark_admission='NATIVE20KEV_ALPHA_ONLY;CONDITIONAL_A4_ADAPTER;G1_NOT_AUTHORIZED',interpolation='NOT_RUN',frame_conversion='NOT_RUN',new_shell_sum='NOT_RUN');rows.append(r)
csvput(B/'EXACT_SOURCE_CELLS.csv',rows,fields)
counts=dict(sorted(collections.Counter(r['source_id'] for r in rows).items()));js(B/'CELL_COUNTS.json',{'total':len(rows),'by_source':counts,'additional_P09_convergence_tokens':300,'cross_section_calculation':'NOT_RUN;source transcription only'})
base=json.loads((B/'_MATRIX_BASE.json').read_text());mf=list(base[0]);new=[]
def add(sid,**kw):
 r={k:'' for k in mf};r.update(source_id=sid,doi=files[sid]['doi'],source_sha256=files[sid]['sha256'],source_class='PUBLISHED_VERSION_RECOVERED',projectile='He2+',target_initial_state='H(1s)',benchmark_admission='SCOPED_SOURCE_AUTHORITY_ONLY;G1_NOT_AUTHORIZED');r.update(kw);new.append(r)
add('P04',isotope='alpha/4He context;H;D/T explicitly outside calculation;exact masses unspecified',target_initial_state='H nativeP04;H(1s) explicitly bound by P01 introduction cross-reference',final_shell_subshell='A3 native1s,2s,2p,n2,3s,3p,3d,n3,n4,n5,CTMCn6..20,totaln1..5,totaln1..20',native_axis='keV/u:1,2,5,10,25,50,70,100,200,500,700,1000;only5cells transcribed',energy_frame='native impact energy;LAB_VS_CM_NOT_EXPLICIT;NO_CONVERSION',method='LTDSE;AOCC-A importedToshima1995NIFS-DATA-26;AOCC-B;CTMC',basis_channel_count='LTDSE320^3 with512^3 check;AOCC-B239=74projectile+165target;AOCC-A source report',continuum='LTDSE spatialgrid;AOCC pseudostates;CTMC classicalcontinuum;quantum n1..20 totals use normalizedCTMCtail',trajectory='LTDSE full trajectory equation not printed here;CTMC classical trajectories;no stronger common assumption assigned',reported_uncertainty='No percellerrors;authors dominant-channel accuracy assessments not certified bounds;method spread not Gaussian',exact_5_keV_u='YES_NATIVE5_TABLE_A3;frame/state provenance limitations retained',exact_0_5_keV_u='NO_NATIVE_ROW',table_page_evidence='AppendixA1-A12 PDF8-11;A3 PDF8 printed7;P01 introduction H1s binding',machine_readable_status='63_NONBLANK_CELLS_ALL27_A3_ROWS;other11tables NOT_TRANSCRIBED',unresolved='Lab/CM not explicit;state cross-source binding;finite masses unspecified;AOCC-A secondary import;no rowcertificate')
add('P07',isotope=M['P07']['system']['isotope_statement'],final_shell_subshell='He1s,n2,n3,n4,n5,total;ionization andH-excitation separate',native_axis='relativevelocitya.u.26rows:0.2313..1.2046;see METADATA_REVIEW',energy_frame='relative nuclear velocity;no native energy column',method='multichannel perturbed-stationary-state close coupling;no ETF employed',basis_channel_count='35He-bound+10H-bound+35L2pseudoionization',continuum='35LCAOpseudostates;limitedcontinuum',trajectory='semiclassical eikonal straightline constantvelocity',reported_uncertainty='No row-specificcertified bound;basis diagnostics not crosssection certificate',exact_5_keV_u='NO_NATIVE_ENERGY_ROW;NO_ADAPTER_RUN',exact_0_5_keV_u='NO_NATIVE_ENERGY_ROW;NO_ADAPTER_RUN',table_page_evidence='TableIII PDF8 printed1371;methodPDF3,5-7',machine_readable_status='GRID_AND_METADATA_INDEXED;NO_CELLS_IN_EXACT_SOURCE_CELLS',unresolved='Nativevelocityretained;noapproximateenergyadmission;finitebasisuncertainty')
add('P08',isotope=p08['system']['isotope_statement'],final_shell_subshell='native1s,2s,2p,3s,3p,3d,beyond3d,All;no native n2/n3 shell totals',native_axis='alpha labkeV:3,8,20,40,70,100,200,400,800,1200,1600,2400;only20rows transcribed',energy_frame='projectile laboratory keV;notnativekeV/u',method='two-center coupled-Sturmian pseudostates',basis_channel_count='107=57H+50He production;151asymmetriccomparison not automatically superior',continuum='positiveenergy Sturmianpseudostates;source threshold/tail corrections',trajectory='straightclassicalpath',reported_uncertainty='Roughbasisestimatesnotcertificate;151state n3 deemedunreliable dueomittedtargetexcitation',exact_5_keV_u='CONDITIONAL_A4_ADAPTER_ONLY;20keVnative;NO_ENERGY_CONVERSION',exact_0_5_keV_u='NO_NATIVE2KEV_ROW',table_page_evidence='TableII PDF5 printed062702-5;labenergyPDF1;TableIVgraphicalinterpolationexcluded',machine_readable_status='16_NATIVE20KEV_CELLS_VERIFIED;otherenergies NOT_TRANSCRIBED',unresolved='ExplicitA4massnormalizationneededbeforecomparison;no printedn2/n3shellsums;ETFprescriptionnotrecoveredinmethodsummary')
add('P10',isotope=M['P10']['isotopes'],final_shell_subshell='capture/excitation/ionization;nlmdata available onlybyrequest;inverseH+lane separate',native_axis='10-1000keVamu^-1',energy_frame=M['P10']['energy_frame'],method='WP-CCC',basis_channel_count='1910states=955eachcenter;Nb10,Nc20,lmax5',continuum='stationaryCoulombwavepacketsbothcenters',trajectory='z=vt;z-150..150a.u.;impactintegration',reported_uncertainty=M['P10']['uncertainty'],exact_5_keV_u='OUTSIDE_PUBLISHED_RANGE',exact_0_5_keV_u='OUTSIDE_PUBLISHED_RANGE',table_page_evidence='Figures1-18;methodsPDF3-4;dataavailabilityPDF11',machine_readable_status='NO_NUMERIC_TABLES;AUTHOR_REQUEST_DATA_NOT_ACQUIRED;NO_DIGITIZATION',unresolved='rawnlmdata unavailable;requestedenergies outside range')
add('P22',isotope='3He energy-equivalent convention;some4He beams mappedtoequalvelocity by source',final_shell_subshell='Htotalcapture,He2s;H2columns separate;Table2He+excitation excluded',native_axis='3He total labenergykeV;5.0token isnot5keV/u;15keV absentbetween14and16',energy_frame='incident laboratory energy in3He convention',method=M['P22']['method'],basis_channel_count='EXPERIMENT_NOT_APPLICABLE',continuum='EXPERIMENT_CHARGE_STATE_CAPTURE;notfinite-shelltheorytotal',trajectory='accelerator beam through gas target',reported_uncertainty='Htotalabsolute15%;H2s17%;individualreproducibilitytableerrors distinct;no combination',exact_5_keV_u='NO_NATIVE15KEV3HE_ROW_UNDER_A3;NO_CONVERSION',exact_0_5_keV_u='NO_NATIVE1.5KEV3HE_ROW_UNDER_A3',table_page_evidence='Table1 PDF7 printed126;Table2 PDF11 distinctprocess',machine_readable_status='METADATA_AND_EXCLUSION_CHECKED;NO_CELLS_IN_EXACT_SOURCE_CELLS',unresolved='isotope/massadapter;blankHtotalatnative5keVnotzero;no interpolation')
matrix=sorted(base+new,key=lambda r:r['source_id']);assert len(matrix)==13
csvput(B/'BENCHMARK_MATRIX.csv',matrix,mf);shutil.copy2(B/'BENCHMARK_MATRIX.csv',P/'BASS_HE_BENCHMARK_MATRIX.csv')
(B/'code').mkdir(exist_ok=True);shutil.copy2(W/'build_b1.py',B/'code/build_b1_historical.py')
js(B/'evidence/P03_verified_cells.json',{'source_id':'P03','table':'II','pdf_page':9,'scope':'HSCC source-authored column only','rows':{r['energy_token']:r['value_token'] for r in rows if r['source_id']=='P03'}})
print(json.dumps({'cells':len(rows),'by_source':counts,'matrix_rows':len(matrix)},indent=2))
